//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Ambient.Domain")]
    public partial class CharacterInitiationBehavior {
        
        private string initialGreetingField;
        
        private CharacterStateType initialStateField;
        
        public CharacterInitiationBehavior() {
            this.initialStateField = CharacterStateType.Neutral;
        }
        
        /// <remarks/>
        public string InitialGreeting {
            get {
                return this.initialGreetingField;
            }
            set {
                this.initialGreetingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CharacterStateType.Neutral)]
        public CharacterStateType InitialState {
            get {
                return this.initialStateField;
            }
            set {
                this.initialStateField = value;
            }
        }
    }
}
