//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AvatarBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Character))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class CharacterBase : EntityBase {
        
        private CharacterEffects archetypeBiasField;
        
        private CharacterStats statsField;
        
        private ItemCollection capabilitiesField;
        
        private BaseArchetypeType archetypeRefField;
        
        private bool archetypeRefFieldSpecified;
        
        private string affinityRefField;
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        public CharacterBase() {
            this.xField = 0D;
            this.yField = 0D;
            this.zField = 0D;
        }
        
        /// <remarks/>
        public CharacterEffects ArchetypeBias {
            get {
                return this.archetypeBiasField;
            }
            set {
                this.archetypeBiasField = value;
            }
        }
        
        /// <remarks/>
        public CharacterStats Stats {
            get {
                return this.statsField;
            }
            set {
                this.statsField = value;
            }
        }
        
        /// <remarks/>
        public ItemCollection Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BaseArchetypeType ArchetypeRef {
            get {
                return this.archetypeRefField;
            }
            set {
                this.archetypeRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArchetypeRefSpecified {
            get {
                return this.archetypeRefFieldSpecified;
            }
            set {
                this.archetypeRefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AffinityRef {
            get {
                return this.affinityRefField;
            }
            set {
                this.affinityRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
}
