//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class Character : CharacterBase {
        
        private Interactable interactableField;
        
        private CharacterTrait[] traitsField;
        
        private string[] tagsField;
        
        private CharacterTrigger[] battleDialogueField;
        
        private CharacterInitiationBehavior initiationBehaviorField;
        
        private string modelRefField;
        
        private int respawnIntervalSecondsField;
        
        public Character() {
            this.respawnIntervalSecondsField = 0;
        }
        
        /// <remarks/>
        public Interactable Interactable {
            get {
                return this.interactableField;
            }
            set {
                this.interactableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Trait", IsNullable=false)]
        public CharacterTrait[] Traits {
            get {
                return this.traitsField;
            }
            set {
                this.traitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Trigger", IsNullable=false)]
        public CharacterTrigger[] BattleDialogue {
            get {
                return this.battleDialogueField;
            }
            set {
                this.battleDialogueField = value;
            }
        }
        
        /// <remarks/>
        public CharacterInitiationBehavior InitiationBehavior {
            get {
                return this.initiationBehaviorField;
            }
            set {
                this.initiationBehaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModelRef {
            get {
                return this.modelRefField;
            }
            set {
                this.modelRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int RespawnIntervalSeconds {
            get {
                return this.respawnIntervalSecondsField;
            }
            set {
                this.respawnIntervalSecondsField = value;
            }
        }
    }
}
