//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class BaseArchetype : EntityBase {
        
        private CharacterEffects archetypeBiasField;
        
        private string[] defaultSpellCategoriesField;
        
        private BaseArchetypeType archetypeIdField;
        
        private string defaultAffinityRefField;
        
        private int extraAffinitySlotsField;
        
        public BaseArchetype() {
            this.extraAffinitySlotsField = 0;
        }
        
        /// <remarks/>
        public CharacterEffects ArchetypeBias {
            get {
                return this.archetypeBiasField;
            }
            set {
                this.archetypeBiasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", IsNullable=false)]
        public string[] DefaultSpellCategories {
            get {
                return this.defaultSpellCategoriesField;
            }
            set {
                this.defaultSpellCategoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BaseArchetypeType ArchetypeId {
            get {
                return this.archetypeIdField;
            }
            set {
                this.archetypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultAffinityRef {
            get {
                return this.defaultAffinityRefField;
            }
            set {
                this.defaultAffinityRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int ExtraAffinitySlots {
            get {
                return this.extraAffinitySlotsField;
            }
            set {
                this.extraAffinitySlotsField = value;
            }
        }
    }
}
