//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class ProceduralSettings {
        
        private ProceduralGenerationMode proceduralGenerationModeField;
        
        private double latitudeDegreesToUnitsField;
        
        private double longitudeDegreesToUnitsField;
        
        public ProceduralSettings() {
            this.proceduralGenerationModeField = ProceduralGenerationMode.Rugged;
            this.latitudeDegreesToUnitsField = 250D;
            this.longitudeDegreesToUnitsField = 250D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ProceduralGenerationMode.Rugged)]
        public ProceduralGenerationMode ProceduralGenerationMode {
            get {
                return this.proceduralGenerationModeField;
            }
            set {
                this.proceduralGenerationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(250D)]
        public double LatitudeDegreesToUnits {
            get {
                return this.latitudeDegreesToUnitsField;
            }
            set {
                this.latitudeDegreesToUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(250D)]
        public double LongitudeDegreesToUnits {
            get {
                return this.longitudeDegreesToUnitsField;
            }
            set {
                this.longitudeDegreesToUnitsField = value;
            }
        }
    }
}
