//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SagaArc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SagaTriggerPattern))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SagaFeature))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SagaTrigger))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AvatarArchetype))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Faction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusEffect))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CombatStance))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharacterArchetype))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DialogueTree))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Quest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Achievement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharacterBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AvatarBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Character))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoadoutSlot))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CharacterAffinity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AcquirableBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QuestToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Acquirable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DegradableAcquirable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tool))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Equipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Spell))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StackableAcquirable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuildingMaterial))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Consumable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorldConfiguration))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class EntityBase {
        
        private string refNameField;
        
        private string displayNameField;
        
        private string descriptionField;
        
        private string extensionDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefName {
            get {
                return this.refNameField;
            }
            set {
                this.refNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }
}
