//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class Consumable : StackableAcquirable {
        
        private CharacterEffects effectsField;
        
        private float durabilityLossField;
        
        private ItemUseType useTypeField;
        
        public Consumable() {
            this.durabilityLossField = ((float)(0.01F));
            this.useTypeField = ItemUseType.Defensive;
        }
        
        /// <remarks/>
        public CharacterEffects Effects {
            get {
                return this.effectsField;
            }
            set {
                this.effectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.01")]
        public float DurabilityLoss {
            get {
                return this.durabilityLossField;
            }
            set {
                this.durabilityLossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ItemUseType.Defensive)]
        public ItemUseType UseType {
            get {
                return this.useTypeField;
            }
            set {
                this.useTypeField = value;
            }
        }
    }
}
