//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    [System.Xml.Serialization.XmlRootAttribute("Consumables", Namespace="Ambient.Domain", IsNullable=false)]
    public partial class ConsumableCatalog {
        
        private Consumable[] consumableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Consumable")]
        public Consumable[] Consumable {
            get {
                return this.consumableField;
            }
            set {
                this.consumableField = value;
            }
        }
    }
}
