//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class AvatarBase : CharacterBase {
        
        private AchievementEntry[] achievementsField;
        
        private QuestEntry[] questsField;
        
        private SagaArcInventory sagaArcsField;
        
        private Summon[] summonsField;
        
        private PartyInventory partyField;
        
        private string archetypeRef1Field;
        
        private string activeAffinityRefField;
        
        private string currentToolRefField;
        
        private string currentBuildingMaterialRefField;
        
        private float velXField;
        
        private float velYField;
        
        private float velZField;
        
        private float viewXField;
        
        private float viewYField;
        
        private float viewZField;
        
        private float playTimeHoursField;
        
        private long blocksPlacedField;
        
        private long blocksDestroyedField;
        
        private float distanceTraveledField;
        
        public AvatarBase() {
            this.velXField = ((float)(0F));
            this.velYField = ((float)(0F));
            this.velZField = ((float)(0F));
            this.viewXField = ((float)(0F));
            this.viewYField = ((float)(0F));
            this.viewZField = ((float)(1F));
            this.playTimeHoursField = ((float)(0F));
            this.blocksPlacedField = ((long)(0));
            this.blocksDestroyedField = ((long)(0));
            this.distanceTraveledField = ((float)(0F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Achievement", IsNullable=false)]
        public AchievementEntry[] Achievements {
            get {
                return this.achievementsField;
            }
            set {
                this.achievementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Quest", IsNullable=false)]
        public QuestEntry[] Quests {
            get {
                return this.questsField;
            }
            set {
                this.questsField = value;
            }
        }
        
        /// <remarks/>
        public SagaArcInventory SagaArcs {
            get {
                return this.sagaArcsField;
            }
            set {
                this.sagaArcsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Summon[] Summons {
            get {
                return this.summonsField;
            }
            set {
                this.summonsField = value;
            }
        }
        
        /// <remarks/>
        public PartyInventory Party {
            get {
                return this.partyField;
            }
            set {
                this.partyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ArchetypeRef")]
        public string ArchetypeRef1 {
            get {
                return this.archetypeRef1Field;
            }
            set {
                this.archetypeRef1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ActiveAffinityRef {
            get {
                return this.activeAffinityRefField;
            }
            set {
                this.activeAffinityRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrentToolRef {
            get {
                return this.currentToolRefField;
            }
            set {
                this.currentToolRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrentBuildingMaterialRef {
            get {
                return this.currentBuildingMaterialRefField;
            }
            set {
                this.currentBuildingMaterialRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float VelX {
            get {
                return this.velXField;
            }
            set {
                this.velXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float VelY {
            get {
                return this.velYField;
            }
            set {
                this.velYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float VelZ {
            get {
                return this.velZField;
            }
            set {
                this.velZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float ViewX {
            get {
                return this.viewXField;
            }
            set {
                this.viewXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float ViewY {
            get {
                return this.viewYField;
            }
            set {
                this.viewYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float ViewZ {
            get {
                return this.viewZField;
            }
            set {
                this.viewZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float PlayTimeHours {
            get {
                return this.playTimeHoursField;
            }
            set {
                this.playTimeHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long BlocksPlaced {
            get {
                return this.blocksPlacedField;
            }
            set {
                this.blocksPlacedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long BlocksDestroyed {
            get {
                return this.blocksDestroyedField;
            }
            set {
                this.blocksDestroyedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float DistanceTraveled {
            get {
                return this.distanceTraveledField;
            }
            set {
                this.distanceTraveledField = value;
            }
        }
    }
}
