//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class AvatarArchetype : EntityBase {
        
        private CharacterEffects archetypeBiasField;
        
        private CharacterStats spawnStatsField;
        
        private ItemCollection spawnCapabilitiesField;
        
        private CharacterStats respawnStatsField;
        
        private ItemCollection respawnCapabilitiesField;
        
        private string affinityRefField;
        
        /// <remarks/>
        public CharacterEffects ArchetypeBias {
            get {
                return this.archetypeBiasField;
            }
            set {
                this.archetypeBiasField = value;
            }
        }
        
        /// <remarks/>
        public CharacterStats SpawnStats {
            get {
                return this.spawnStatsField;
            }
            set {
                this.spawnStatsField = value;
            }
        }
        
        /// <remarks/>
        public ItemCollection SpawnCapabilities {
            get {
                return this.spawnCapabilitiesField;
            }
            set {
                this.spawnCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        public CharacterStats RespawnStats {
            get {
                return this.respawnStatsField;
            }
            set {
                this.respawnStatsField = value;
            }
        }
        
        /// <remarks/>
        public ItemCollection RespawnCapabilities {
            get {
                return this.respawnCapabilitiesField;
            }
            set {
                this.respawnCapabilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AffinityRef {
            get {
                return this.affinityRefField;
            }
            set {
                this.affinityRefField = value;
            }
        }
    }
}
