//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class Equipment : DegradableAcquirable {
        
        private CharacterEffects effectsField;
        
        private string slotRefField;
        
        private float durabilityLossField;
        
        private ItemUseType useTypeField;
        
        private string statusEffectRefField;
        
        private float statusEffectChanceField;
        
        private bool statusEffectOnCritOnlyField;
        
        private float criticalHitBonusField;
        
        public Equipment() {
            this.durabilityLossField = ((float)(0.01F));
            this.useTypeField = ItemUseType.Defensive;
            this.statusEffectChanceField = ((float)(0F));
            this.statusEffectOnCritOnlyField = false;
            this.criticalHitBonusField = ((float)(0F));
        }
        
        /// <remarks/>
        public CharacterEffects Effects {
            get {
                return this.effectsField;
            }
            set {
                this.effectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SlotRef {
            get {
                return this.slotRefField;
            }
            set {
                this.slotRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0.01")]
        public float DurabilityLoss {
            get {
                return this.durabilityLossField;
            }
            set {
                this.durabilityLossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ItemUseType.Defensive)]
        public ItemUseType UseType {
            get {
                return this.useTypeField;
            }
            set {
                this.useTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusEffectRef {
            get {
                return this.statusEffectRefField;
            }
            set {
                this.statusEffectRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float StatusEffectChance {
            get {
                return this.statusEffectChanceField;
            }
            set {
                this.statusEffectChanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool StatusEffectOnCritOnly {
            get {
                return this.statusEffectOnCritOnlyField;
            }
            set {
                this.statusEffectOnCritOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float CriticalHitBonus {
            get {
                return this.criticalHitBonusField;
            }
            set {
                this.criticalHitBonusField = value;
            }
        }
    }
}
