using System.Text;

namespace Ambient.Application.WorldCreation;

/// <summary>
/// Builds GenerationConfiguration.xml content from world creation parameters.
/// This file is used by Schema.Codex.WorldForge to generate story content.
/// </summary>
public class GenerationConfigurationBuilder
{
    /// <summary>
    /// Build the GenerationConfiguration.xml content.
    /// </summary>
    public string Build(WorldCreationParameters parameters)
    {
        var generationStyle = parameters.LocationGenerationType == "radial"
            ? "RadialExploration"
            : "Trail";

        // Build SourceLocation elements from provided locations
        var sourceLocationsXml = new StringBuilder();
        foreach (var loc in parameters.Locations)
        {
            sourceLocationsXml.AppendLine($@"  <SourceLocation DisplayName=""{EscapeXml(loc.Name)}"" Description=""{EscapeXml(loc.Description)}"" Category=""{loc.Category}"" Kind=""{loc.Kind}"" Lat=""{loc.Latitude}"" Lon=""{loc.Longitude}"" />");
        }

        return $@"<?xml version=""1.0"" encoding=""utf-8""?>
<GenerationConfiguration xmlns=""Ambient.WorldContentGenerator"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance""
    WorldRef=""{parameters.WorldRef}""
    DisplayName=""{EscapeXml(parameters.DisplayName)}""
    Description=""Generated by World Creation Wizard""
    GenerationStyle=""{generationStyle}""
    Spacing=""500""
    Seed=""0""
    Theme=""{parameters.Theme}"">
{sourceLocationsXml}</GenerationConfiguration>";
    }

    private static string EscapeXml(string text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
    }
}
