//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class SagaArcInventory {
        
        private SagaDiscovery[] discoveryField;
        
        private int totalDiscoveredField;
        
        public SagaArcInventory() {
            this.totalDiscoveredField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Discovery")]
        public SagaDiscovery[] Discovery {
            get {
                return this.discoveryField;
            }
            set {
                this.discoveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int TotalDiscovered {
            get {
                return this.totalDiscoveredField;
            }
            set {
                this.totalDiscoveredField = value;
            }
        }
    }
}
