//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class SagaArc : EntityBase {
        
        private string sagaFeatureRefField;
        
        private object[] itemsField;
        
        private double latitudeZField;
        
        private double longitudeXField;
        
        /// <remarks/>
        public string SagaFeatureRef {
            get {
                return this.sagaFeatureRefField;
            }
            set {
                this.sagaFeatureRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SagaTrigger", typeof(SagaTrigger))]
        [System.Xml.Serialization.XmlElementAttribute("SagaTriggerPatternRef", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double LatitudeZ {
            get {
                return this.latitudeZField;
            }
            set {
                this.latitudeZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double LongitudeX {
            get {
                return this.longitudeXField;
            }
            set {
                this.longitudeXField = value;
            }
        }
    }
}
