//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class SagaArcAIMetadata {
        
        private string[] storyThreadRefField;
        
        private string thematicTagsField;
        
        private NarrativeConnection[] narrativeConnectionField;
        
        private NarrativeRole narrativeRoleField;
        
        private bool narrativeRoleFieldSpecified;
        
        private int narrativeSequenceField;
        
        private bool narrativeSequenceFieldSpecified;
        
        private string toneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StoryThreadRef")]
        public string[] StoryThreadRef {
            get {
                return this.storyThreadRefField;
            }
            set {
                this.storyThreadRefField = value;
            }
        }
        
        /// <remarks/>
        public string ThematicTags {
            get {
                return this.thematicTagsField;
            }
            set {
                this.thematicTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NarrativeConnection")]
        public NarrativeConnection[] NarrativeConnection {
            get {
                return this.narrativeConnectionField;
            }
            set {
                this.narrativeConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NarrativeRole NarrativeRole {
            get {
                return this.narrativeRoleField;
            }
            set {
                this.narrativeRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NarrativeRoleSpecified {
            get {
                return this.narrativeRoleFieldSpecified;
            }
            set {
                this.narrativeRoleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NarrativeSequence {
            get {
                return this.narrativeSequenceField;
            }
            set {
                this.narrativeSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NarrativeSequenceSpecified {
            get {
                return this.narrativeSequenceFieldSpecified;
            }
            set {
                this.narrativeSequenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tone {
            get {
                return this.toneField;
            }
            set {
                this.toneField = value;
            }
        }
    }
}
