//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class SagaFeature : EntityBase {
        
        private InteractableBase interactableField;
        
        private SagaFeatureType typeField;
        
        private string categoryTypeField;
        
        private string subTypeField;
        
        private string tagsField;
        
        private string modelRefField;
        
        private string questRefField;
        
        private QuestDifficulty difficultyField;
        
        private int estimatedDurationMinutesField;
        
        private bool estimatedDurationMinutesFieldSpecified;
        
        public SagaFeature() {
            this.difficultyField = QuestDifficulty.Normal;
        }
        
        /// <remarks/>
        public InteractableBase Interactable {
            get {
                return this.interactableField;
            }
            set {
                this.interactableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SagaFeatureType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CategoryType {
            get {
                return this.categoryTypeField;
            }
            set {
                this.categoryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModelRef {
            get {
                return this.modelRefField;
            }
            set {
                this.modelRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QuestRef {
            get {
                return this.questRefField;
            }
            set {
                this.questRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(QuestDifficulty.Normal)]
        public QuestDifficulty Difficulty {
            get {
                return this.difficultyField;
            }
            set {
                this.difficultyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int EstimatedDurationMinutes {
            get {
                return this.estimatedDurationMinutesField;
            }
            set {
                this.estimatedDurationMinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedDurationMinutesSpecified {
            get {
                return this.estimatedDurationMinutesFieldSpecified;
            }
            set {
                this.estimatedDurationMinutesFieldSpecified = value;
            }
        }
    }
}
