//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class CombatStance : EntityBase {
        
        private float strengthMultiplierField;
        
        private float defenseMultiplierField;
        
        private float speedMultiplierField;
        
        private float magicMultiplierField;
        
        public CombatStance() {
            this.strengthMultiplierField = ((float)(1F));
            this.defenseMultiplierField = ((float)(1F));
            this.speedMultiplierField = ((float)(1F));
            this.magicMultiplierField = ((float)(1F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float StrengthMultiplier {
            get {
                return this.strengthMultiplierField;
            }
            set {
                this.strengthMultiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float DefenseMultiplier {
            get {
                return this.defenseMultiplierField;
            }
            set {
                this.defenseMultiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float SpeedMultiplier {
            get {
                return this.speedMultiplierField;
            }
            set {
                this.speedMultiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float MagicMultiplier {
            get {
                return this.magicMultiplierField;
            }
            set {
                this.magicMultiplierField = value;
            }
        }
    }
}
