//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class QuestStage {
        
        private object itemField;
        
        private QuestReward[] rewardsField;
        
        private QuestFailCondition[] failConditionsField;
        
        private string refNameField;
        
        private string displayNameField;
        
        private string nextStageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Branches", typeof(QuestStageBranches))]
        [System.Xml.Serialization.XmlElementAttribute("Objectives", typeof(QuestStageObjectives))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reward", IsNullable=false)]
        public QuestReward[] Rewards {
            get {
                return this.rewardsField;
            }
            set {
                this.rewardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FailCondition", IsNullable=false)]
        public QuestFailCondition[] FailConditions {
            get {
                return this.failConditionsField;
            }
            set {
                this.failConditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefName {
            get {
                return this.refNameField;
            }
            set {
                this.refNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NextStage {
            get {
                return this.nextStageField;
            }
            set {
                this.nextStageField = value;
            }
        }
    }
}
