//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class QuestObjective {
        
        private string refNameField;
        
        private QuestObjectiveType typeField;
        
        private string displayNameField;
        
        private string characterRefField;
        
        private string characterTagField;
        
        private string characterTypeField;
        
        private string dialogueRefField;
        
        private string choiceRefField;
        
        private string nodeRefField;
        
        private string itemRefField;
        
        private string locationRefField;
        
        private string sagaArcRefField;
        
        private string triggerRefField;
        
        private string questTokenRefField;
        
        private int thresholdField;
        
        private bool optionalField;
        
        private bool hiddenField;
        
        public QuestObjective() {
            this.thresholdField = 1;
            this.optionalField = false;
            this.hiddenField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefName {
            get {
                return this.refNameField;
            }
            set {
                this.refNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QuestObjectiveType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CharacterRef {
            get {
                return this.characterRefField;
            }
            set {
                this.characterRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CharacterTag {
            get {
                return this.characterTagField;
            }
            set {
                this.characterTagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CharacterType {
            get {
                return this.characterTypeField;
            }
            set {
                this.characterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DialogueRef {
            get {
                return this.dialogueRefField;
            }
            set {
                this.dialogueRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChoiceRef {
            get {
                return this.choiceRefField;
            }
            set {
                this.choiceRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeRef {
            get {
                return this.nodeRefField;
            }
            set {
                this.nodeRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemRef {
            get {
                return this.itemRefField;
            }
            set {
                this.itemRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocationRef {
            get {
                return this.locationRefField;
            }
            set {
                this.locationRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SagaArcRef {
            get {
                return this.sagaArcRefField;
            }
            set {
                this.sagaArcRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TriggerRef {
            get {
                return this.triggerRefField;
            }
            set {
                this.triggerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QuestTokenRef {
            get {
                return this.questTokenRefField;
            }
            set {
                this.questTokenRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int Threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Optional {
            get {
                return this.optionalField;
            }
            set {
                this.optionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Hidden {
            get {
                return this.hiddenField;
            }
            set {
                this.hiddenField = value;
            }
        }
    }
}
