//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class Quest : EntityBase {
        
        private QuestPrerequisite[] prerequisitesField;
        
        private QuestStages stagesField;
        
        private QuestReward[] rewardsField;
        
        private QuestFailCondition[] failConditionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Prerequisite", IsNullable=false)]
        public QuestPrerequisite[] Prerequisites {
            get {
                return this.prerequisitesField;
            }
            set {
                this.prerequisitesField = value;
            }
        }
        
        /// <remarks/>
        public QuestStages Stages {
            get {
                return this.stagesField;
            }
            set {
                this.stagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reward", IsNullable=false)]
        public QuestReward[] Rewards {
            get {
                return this.rewardsField;
            }
            set {
                this.rewardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FailCondition", IsNullable=false)]
        public QuestFailCondition[] FailConditions {
            get {
                return this.failConditionsField;
            }
            set {
                this.failConditionsField = value;
            }
        }
    }
}
