//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class QuestReward {
        
        private QuestRewardCurrency currencyField;
        
        private QuestRewardEquipment[] equipmentField;
        
        private QuestRewardConsumable[] consumableField;
        
        private QuestRewardQuestToken[] questTokenField;
        
        private QuestRewardAchievement[] achievementField;
        
        private QuestRewardExperience experienceField;
        
        private QuestRewardReputation[] reputationField;
        
        private QuestRewardCondition conditionField;
        
        private string branchRefField;
        
        private string objectiveRefField;
        
        /// <remarks/>
        public QuestRewardCurrency Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Equipment")]
        public QuestRewardEquipment[] Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Consumable")]
        public QuestRewardConsumable[] Consumable {
            get {
                return this.consumableField;
            }
            set {
                this.consumableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuestToken")]
        public QuestRewardQuestToken[] QuestToken {
            get {
                return this.questTokenField;
            }
            set {
                this.questTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Achievement")]
        public QuestRewardAchievement[] Achievement {
            get {
                return this.achievementField;
            }
            set {
                this.achievementField = value;
            }
        }
        
        /// <remarks/>
        public QuestRewardExperience Experience {
            get {
                return this.experienceField;
            }
            set {
                this.experienceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reputation")]
        public QuestRewardReputation[] Reputation {
            get {
                return this.reputationField;
            }
            set {
                this.reputationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QuestRewardCondition Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BranchRef {
            get {
                return this.branchRefField;
            }
            set {
                this.branchRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ObjectiveRef {
            get {
                return this.objectiveRefField;
            }
            set {
                this.objectiveRefField = value;
            }
        }
    }
}
