<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="Ambient.Domain" xmlns="Ambient.Domain" elementFormDefault="qualified">
    <xs:include schemaLocation="../Actors/Characters/Characters.xsd" />
    <xs:include schemaLocation="../Acquirables/QuestToken.xsd" />
    <xs:include schemaLocation="../Acquirables/Attributes.xsd" />
    <xs:include schemaLocation="../Acquirables/ItemCollection.xsd" />
    <xs:include schemaLocation="../CommonTypes.xsd" />
    <xs:include schemaLocation="../Interactable.xsd" />
    <xs:include schemaLocation="../Quests/Quest.xsd" />
    <xs:simpleType name="Meters">
        <xs:annotation>
            <xs:documentation>A non-negative distance measurement in meters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="CharacterSpawn">
        <xs:annotation>
            <xs:documentation>Defines which character to spawn and how many instances to create when a trigger fires.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="CharacterRef" type="CharacterRef" />
        </xs:sequence>
        <xs:attribute name="Count" type="NonNegativeInt" use="optional" default="1">
            <xs:annotation>
                <xs:documentation>Number of instances of this character to spawn.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="SagaTrigger">
        <xs:annotation>
            <xs:documentation>A proximity-based trigger that spawns NPCs when the avatar enters its radius within a SagaArc.</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="EntityBase">
                <xs:sequence>
                    <xs:element name="Spawn" type="CharacterSpawn" minOccurs="1" maxOccurs="unbounded" />
                    <xs:element name="RequiresQuestTokenRef" type="QuestTokenRef" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element name="GivesQuestTokenRef" type="QuestTokenRef" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="EnterRadius" type="Meters" use="required">
                    <xs:annotation>
                        <xs:documentation>Distance in meters from the SagaArc center at which this trigger activates.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>