//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class StatusEffect : EntityBase {
        
        private StatusEffectType typeField;
        
        private int damagePerTurnField;
        
        private int durationTurnsField;
        
        private float strengthModifierField;
        
        private float defenseModifierField;
        
        private float speedModifierField;
        
        private float magicModifierField;
        
        private float accuracyModifierField;
        
        private int maxStacksField;
        
        private bool cleansableField;
        
        private ApplicationMethod applicationMethodField;
        
        private StatusEffectCategory categoryField;
        
        private bool categoryFieldSpecified;
        
        public StatusEffect() {
            this.damagePerTurnField = 0;
            this.durationTurnsField = 3;
            this.strengthModifierField = ((float)(0F));
            this.defenseModifierField = ((float)(0F));
            this.speedModifierField = ((float)(0F));
            this.magicModifierField = ((float)(0F));
            this.accuracyModifierField = ((float)(0F));
            this.maxStacksField = 1;
            this.cleansableField = true;
            this.applicationMethodField = ApplicationMethod.StartOfTurn;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusEffectType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int DamagePerTurn {
            get {
                return this.damagePerTurnField;
            }
            set {
                this.damagePerTurnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(3)]
        public int DurationTurns {
            get {
                return this.durationTurnsField;
            }
            set {
                this.durationTurnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float StrengthModifier {
            get {
                return this.strengthModifierField;
            }
            set {
                this.strengthModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float DefenseModifier {
            get {
                return this.defenseModifierField;
            }
            set {
                this.defenseModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float SpeedModifier {
            get {
                return this.speedModifierField;
            }
            set {
                this.speedModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float MagicModifier {
            get {
                return this.magicModifierField;
            }
            set {
                this.magicModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
        public float AccuracyModifier {
            get {
                return this.accuracyModifierField;
            }
            set {
                this.accuracyModifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int MaxStacks {
            get {
                return this.maxStacksField;
            }
            set {
                this.maxStacksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Cleansable {
            get {
                return this.cleansableField;
            }
            set {
                this.cleansableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ApplicationMethod.StartOfTurn)]
        public ApplicationMethod ApplicationMethod {
            get {
                return this.applicationMethodField;
            }
            set {
                this.applicationMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusEffectCategory Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategorySpecified {
            get {
                return this.categoryFieldSpecified;
            }
            set {
                this.categoryFieldSpecified = value;
            }
        }
    }
}
