//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class DialogueNode {
        
        private DialogueCondition[] conditionField;
        
        private string[] textField;
        
        private DialogueAction[] actionField;
        
        private DialogueChoice[] choiceField;
        
        private string nodeIdField;
        
        private string nextNodeIdField;
        
        private ConditionLogic conditionLogicField;
        
        public DialogueNode() {
            this.conditionLogicField = ConditionLogic.AND;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Condition")]
        public DialogueCondition[] Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public DialogueAction[] Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choice")]
        public DialogueChoice[] Choice {
            get {
                return this.choiceField;
            }
            set {
                this.choiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeId {
            get {
                return this.nodeIdField;
            }
            set {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NextNodeId {
            get {
                return this.nextNodeIdField;
            }
            set {
                this.nextNodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ConditionLogic.AND)]
        public ConditionLogic ConditionLogic {
            get {
                return this.conditionLogicField;
            }
            set {
                this.conditionLogicField = value;
            }
        }
    }
}
