//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public enum DialogueActionType {
        
        /// <remarks/>
        GiveQuestToken,
        
        /// <remarks/>
        TakeQuestToken,
        
        /// <remarks/>
        GiveConsumable,
        
        /// <remarks/>
        TakeConsumable,
        
        /// <remarks/>
        GiveMaterial,
        
        /// <remarks/>
        TakeMaterial,
        
        /// <remarks/>
        GiveBlock,
        
        /// <remarks/>
        TakeBlock,
        
        /// <remarks/>
        GiveEquipment,
        
        /// <remarks/>
        TakeEquipment,
        
        /// <remarks/>
        GiveTool,
        
        /// <remarks/>
        TakeTool,
        
        /// <remarks/>
        GiveSpell,
        
        /// <remarks/>
        TakeSpell,
        
        /// <remarks/>
        TransferCurrency,
        
        /// <remarks/>
        UnlockAchievement,
        
        /// <remarks/>
        AcceptQuest,
        
        /// <remarks/>
        CompleteQuest,
        
        /// <remarks/>
        AbandonQuest,
        
        /// <remarks/>
        OpenMerchantTrade,
        
        /// <remarks/>
        StartBossBattle,
        
        /// <remarks/>
        StartCombat,
        
        /// <remarks/>
        SpawnCharacters,
        
        /// <remarks/>
        AssignTrait,
        
        /// <remarks/>
        RemoveTrait,
        
        /// <remarks/>
        SetCharacterState,
        
        /// <remarks/>
        ChangeReputation,
        
        /// <remarks/>
        ChangeStance,
        
        /// <remarks/>
        ChangeAffinity,
        
        /// <remarks/>
        CastSpell,
        
        /// <remarks/>
        SummonAlly,
        
        /// <remarks/>
        EndBattle,
        
        /// <remarks/>
        HealSelf,
        
        /// <remarks/>
        ApplyStatusEffect,
    }
}
