<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="Ambient.Domain" xmlns="Ambient.Domain" elementFormDefault="qualified">
    <xs:include schemaLocation="EntityBase.xsd" />
    <xs:simpleType name="WorldConfigurationRef">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="HeightMapSettings">
		<xs:attribute name="FileName" type="xs:string" use="required" />
		<xs:attribute name="HorizontalScale" type="xs:double" use="required" />
        <xs:attribute name="VerticalScale" type="xs:double" use="required" />
        <xs:attribute name="VerticalShift" type="xs:double" use="required" />
    </xs:complexType>
    <xs:complexType name="ProceduralSettings">
        <xs:attribute name="LatitudeDegreesToUnits" type="xs:double" default="250" />
        <xs:attribute name="LongitudeDegreesToUnits" type="xs:double" default="250" />
    </xs:complexType>
    <xs:complexType name="WorldConfiguration">
        <xs:complexContent>
            <xs:extension base="EntityBase">
                <xs:sequence>
                    <xs:choice>
                        <xs:element name="HeightMapSettings" type="HeightMapSettings" />
                        <xs:element name="ProceduralSettings" type="ProceduralSettings" />
                    </xs:choice>
                </xs:sequence>
				<xs:attribute name="ContentPackLibrary" type="xs:string" default="default" />
				<xs:attribute name="ContentPackTheme" type="xs:string" />
				<xs:attribute name="Namespace" type="xs:string" use="required" />
                <xs:attribute name="CurrencyName" type="xs:string" default="Credit" />
                <xs:attribute name="StartDate" type="xs:date" default="0001-05-01" />
                <xs:attribute name="SpawnLatitude" type="xs:double" use="required" />
                <xs:attribute name="SpawnLongitude" type="xs:double" use="required" />
                <xs:attribute name="SecondsInHour" type="xs:int" default="60" />
				<xs:attribute name="ClimateModel" type="ClimateModel" default="Earth" />
				<xs:attribute name="AllowTeleporting" type="xs:boolean" default="false" />
				<xs:attribute name="DisplayOrder" type="xs:int" default="100" />
				<xs:attribute name="WeightUnitName" type="xs:string" default="kg" />
				<xs:attribute name="BlockWeight" type="xs:int" default="1000" />
				<xs:attribute name="EquipmentWeight" type="xs:int" default="2000" />
				<xs:attribute name="ToolWeight" type="xs:int" default="1500" />
				<xs:attribute name="SpellWeight" type="xs:int" default="100" />
				<xs:attribute name="ConsumableWeight" type="xs:int" default="250" />
				<xs:attribute name="BuildingMaterialWeight" type="xs:int" default="500" />
			</xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>