//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DegradableAcquirable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tool))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Equipment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Spell))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StackableAcquirable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuildingMaterial))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Consumable))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    public partial class Acquirable : AcquirableBase {
        
        private string affinityRefField;
        
        private ItemRarityType rarityField;
        
        private int wholesalePriceField;
        
        private float merchantMarkupMultiplierField;
        
        public Acquirable() {
            this.rarityField = ItemRarityType.Common;
            this.wholesalePriceField = 2147483647;
            this.merchantMarkupMultiplierField = ((float)(1.5F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AffinityRef {
            get {
                return this.affinityRefField;
            }
            set {
                this.affinityRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ItemRarityType.Common)]
        public ItemRarityType Rarity {
            get {
                return this.rarityField;
            }
            set {
                this.rarityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(2147483647)]
        public int WholesalePrice {
            get {
                return this.wholesalePriceField;
            }
            set {
                this.wholesalePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1.5")]
        public float MerchantMarkupMultiplier {
            get {
                return this.merchantMarkupMultiplierField;
            }
            set {
                this.merchantMarkupMultiplierField = value;
            }
        }
    }
}
