//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Ambient.Domain", IsNullable=false)]
    public partial class WorldTemplate {
        
        private TemplateMetadata metadataField;
        
        private GameplayComponents gameplayField;
        
        /// <remarks/>
        public TemplateMetadata Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        public GameplayComponents Gameplay {
            get {
                return this.gameplayField;
            }
            set {
                this.gameplayField = value;
            }
        }
    }
}
