//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Ambient.Domain {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Ambient.Domain")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Ambient.Domain", IsNullable=false)]
    public partial class WorldConfiguration : EntityBase {
        
        private object itemField;
        
        private string templateField;
        
        private string consumableItemsRefField;
        
        private string spellsRefField;
        
        private string equipmentRefField;
        
        private string questTokensRefField;
        
        private string charactersRefField;
        
        private string characterArchetypesRefField;
        
        private string characterAffinitiesRefField;
        
        private string combatStancesRefField;
        
        private string loadoutSlotsRefField;
        
        private string toolsRefField;
        
        private string buildingMaterialsRefField;
        
        private string dialogueTreesRefField;
        
        private string avatarArchetypesRefField;
        
        private string sagaFeaturesRefField;
        
        private string achievementsRefField;
        
        private string questsRefField;
        
        private string sagaArcsRefField;
        
        private string factionsRefField;
        
        private string sagaTriggerPatternsRefField;
        
        private string currencyNameField;
        
        private WorldGameMode gameModeField;
        
        private WorldDataSource dataSourceField;
        
        private System.DateTime startDateField;
        
        private string modField;
        
        private double spawnLatitudeField;
        
        private double spawnLongitudeField;
        
        private int chunkHeightField;
        
        private bool chunkHeightFieldSpecified;
        
        private BlockMode blockModeField;
        
        private int ownerChunkCountField;
        
        private int guestChunkCountField;
        
        private EffectLevel nonOwnerChunkEffectLevelField;
        
        private int maxPlayersField;
        
        private int maxCapturedSummonsField;
        
        private WorldLifeMode lifeModeField;
        
        private int secondsInHourField;
        
        private string regionField;
        
        private string difficultyField;
        
        private string recommendedForField;
        
        private float seedField;
        
        private float blockScaleFactorField;
        
        private float gravityField;
        
        private bool shortNightsAndWinterField;
        
        public WorldConfiguration() {
            this.consumableItemsRefField = "Default";
            this.spellsRefField = "Default";
            this.equipmentRefField = "Default";
            this.questTokensRefField = "Default";
            this.charactersRefField = "Default";
            this.characterArchetypesRefField = "Default";
            this.characterAffinitiesRefField = "Default";
            this.combatStancesRefField = "Default";
            this.loadoutSlotsRefField = "Default";
            this.toolsRefField = "Default";
            this.buildingMaterialsRefField = "Default";
            this.dialogueTreesRefField = "Default";
            this.avatarArchetypesRefField = "Default";
            this.sagaFeaturesRefField = "Default";
            this.achievementsRefField = "Default";
            this.questsRefField = "Default";
            this.sagaArcsRefField = "Default";
            this.factionsRefField = "Default";
            this.sagaTriggerPatternsRefField = "Default";
            this.currencyNameField = "Credit";
            this.gameModeField = WorldGameMode.Play;
            this.dataSourceField = WorldDataSource.Generated;
            this.startDateField = new System.DateTime(103680000000000);
            this.modField = "Ambient.Game.Mod.dll";
            this.blockModeField = BlockMode.ChamferedEdges;
            this.ownerChunkCountField = 256;
            this.guestChunkCountField = 1;
            this.nonOwnerChunkEffectLevelField = EffectLevel.Medium;
            this.maxPlayersField = 100;
            this.maxCapturedSummonsField = 12;
            this.lifeModeField = WorldLifeMode.Living;
            this.secondsInHourField = 60;
            this.difficultyField = "Normal";
            this.blockScaleFactorField = ((float)(1F));
            this.gravityField = ((float)(20F));
            this.shortNightsAndWinterField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HeightMapSettings", typeof(HeightMapSettings))]
        [System.Xml.Serialization.XmlElementAttribute("ProceduralSettings", typeof(ProceduralSettings))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string ConsumableItemsRef {
            get {
                return this.consumableItemsRefField;
            }
            set {
                this.consumableItemsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string SpellsRef {
            get {
                return this.spellsRefField;
            }
            set {
                this.spellsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string EquipmentRef {
            get {
                return this.equipmentRefField;
            }
            set {
                this.equipmentRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string QuestTokensRef {
            get {
                return this.questTokensRefField;
            }
            set {
                this.questTokensRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string CharactersRef {
            get {
                return this.charactersRefField;
            }
            set {
                this.charactersRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string CharacterArchetypesRef {
            get {
                return this.characterArchetypesRefField;
            }
            set {
                this.characterArchetypesRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string CharacterAffinitiesRef {
            get {
                return this.characterAffinitiesRefField;
            }
            set {
                this.characterAffinitiesRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string CombatStancesRef {
            get {
                return this.combatStancesRefField;
            }
            set {
                this.combatStancesRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string LoadoutSlotsRef {
            get {
                return this.loadoutSlotsRefField;
            }
            set {
                this.loadoutSlotsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string ToolsRef {
            get {
                return this.toolsRefField;
            }
            set {
                this.toolsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string BuildingMaterialsRef {
            get {
                return this.buildingMaterialsRefField;
            }
            set {
                this.buildingMaterialsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string DialogueTreesRef {
            get {
                return this.dialogueTreesRefField;
            }
            set {
                this.dialogueTreesRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string AvatarArchetypesRef {
            get {
                return this.avatarArchetypesRefField;
            }
            set {
                this.avatarArchetypesRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string SagaFeaturesRef {
            get {
                return this.sagaFeaturesRefField;
            }
            set {
                this.sagaFeaturesRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string AchievementsRef {
            get {
                return this.achievementsRefField;
            }
            set {
                this.achievementsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string QuestsRef {
            get {
                return this.questsRefField;
            }
            set {
                this.questsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string SagaArcsRef {
            get {
                return this.sagaArcsRefField;
            }
            set {
                this.sagaArcsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string FactionsRef {
            get {
                return this.factionsRefField;
            }
            set {
                this.factionsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Default")]
        public string SagaTriggerPatternsRef {
            get {
                return this.sagaTriggerPatternsRefField;
            }
            set {
                this.sagaTriggerPatternsRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Credit")]
        public string CurrencyName {
            get {
                return this.currencyNameField;
            }
            set {
                this.currencyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WorldGameMode.Play)]
        public WorldGameMode GameMode {
            get {
                return this.gameModeField;
            }
            set {
                this.gameModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WorldDataSource.Generated)]
        public WorldDataSource DataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-05-01")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Ambient.Game.Mod.dll")]
        public string Mod {
            get {
                return this.modField;
            }
            set {
                this.modField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double SpawnLatitude {
            get {
                return this.spawnLatitudeField;
            }
            set {
                this.spawnLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double SpawnLongitude {
            get {
                return this.spawnLongitudeField;
            }
            set {
                this.spawnLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ChunkHeight {
            get {
                return this.chunkHeightField;
            }
            set {
                this.chunkHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChunkHeightSpecified {
            get {
                return this.chunkHeightFieldSpecified;
            }
            set {
                this.chunkHeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(BlockMode.ChamferedEdges)]
        public BlockMode BlockMode {
            get {
                return this.blockModeField;
            }
            set {
                this.blockModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(256)]
        public int OwnerChunkCount {
            get {
                return this.ownerChunkCountField;
            }
            set {
                this.ownerChunkCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int GuestChunkCount {
            get {
                return this.guestChunkCountField;
            }
            set {
                this.guestChunkCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(EffectLevel.Medium)]
        public EffectLevel NonOwnerChunkEffectLevel {
            get {
                return this.nonOwnerChunkEffectLevelField;
            }
            set {
                this.nonOwnerChunkEffectLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(100)]
        public int MaxPlayers {
            get {
                return this.maxPlayersField;
            }
            set {
                this.maxPlayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(12)]
        public int MaxCapturedSummons {
            get {
                return this.maxCapturedSummonsField;
            }
            set {
                this.maxCapturedSummonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WorldLifeMode.Living)]
        public WorldLifeMode LifeMode {
            get {
                return this.lifeModeField;
            }
            set {
                this.lifeModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(60)]
        public int SecondsInHour {
            get {
                return this.secondsInHourField;
            }
            set {
                this.secondsInHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Normal")]
        public string Difficulty {
            get {
                return this.difficultyField;
            }
            set {
                this.difficultyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RecommendedFor {
            get {
                return this.recommendedForField;
            }
            set {
                this.recommendedForField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float BlockScaleFactor {
            get {
                return this.blockScaleFactorField;
            }
            set {
                this.blockScaleFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "20")]
        public float Gravity {
            get {
                return this.gravityField;
            }
            set {
                this.gravityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShortNightsAndWinter {
            get {
                return this.shortNightsAndWinterField;
            }
            set {
                this.shortNightsAndWinterField = value;
            }
        }
    }
}
