using Ambient.Domain;
using Ambient.StoryGenerator;

namespace Ambient.Saga.StoryGenerator.Models;

/// <summary>
/// Context object containing all data needed for XML generation.
/// Avoids having to pass many parameters to each generator.
/// </summary>
public class GenerationContext
{
    public WorldConfiguration WorldConfig { get; set; } = null!;
    public NarrativeStructure Narrative { get; set; } = null!;
    public RefNameGenerator RefNameGenerator { get; set; } = null!;
    public ThemeContent? Theme { get; set; }

    /// <summary>
    /// All unique locations generated by path service (for SagaFeatures, Sagas)
    /// </summary>
    public List<SourceLocation> UniqueLocations { get; set; } = new();

    /// <summary>
    /// Original source locations from GenerationConfiguration (for Quests)
    /// </summary>
    public SourceLocation[] SourceLocations { get; set; } = Array.Empty<SourceLocation>();
}
